### ISSUE TITLE
Extract installation of 01proxy definition into own script

### ISSUE THREAD

**Issue by fwolfst** [ecovillage/apt-proxy-client#2]
Would be nice to have a script that installs `/etc/apt/apt.conf.d/01proxy` irrespective of presence of `search` in `resolv.conf`.

**Comment by libengine** [comment]
fixed by executing '/etc/network/if-up.d/apt-proxy-client' in 'after-install.
Does also "apt update".

**Comment by fwolfst** [comment]
I disagree. It would be great to have script that installs the file, irrespective of what environment we are in.
Also, I now think doing the apt update at bootup is too intrusive. I would disable that (or make it configurable, but I'd prefer it do be removed).

**Comment by libengine** [comment]
I believe apt wouldn't work in case the machine is outside of 7Linden lan.

**Comment by libengine** [comment]
Fixed that using another if-case. I know you don't like that, but most of the apt-proxy-conf and the install-proxy-conf scripts would be identical.
In my opinion the additional if-case and a symlink are a good middle ground.

**Comment by fwolfst** [comment]
Solution is "okay". I'd prefer that the whole `gen_proxy_conf` (and configuration parsing) would be in its own script, which is then called by `apt-proxy-client`. `apt-proxy-client` would more or less only call the `at-home` and the `gen_proxy_conf` script in an if-else-tree. And probably gen_proxy_conf would not be the best name for the script.

I find it okay as-is, but not the best solution.
