### ISSUE TITLE
Use 7linden-at-home for checking whether we are at home

### ISSUE THREAD

**Issue by fwolfst** [ecovillage/apt-proxy-client#4]
Instead of duplicating behaviour in https://github.com/ecovillage/7linden-at-home, we should depend on it and use it (checking return value of opt/7linden-at-home/bin/7linden-at-home).

**Comment by fwolfst** [comment]
@libengine The idea is that we can then call `/opt/7linden-at-home/bin/7linden-at-home` (https://github.com/ecovillage/7linden-at-home/blob/master/opt/7linden-at-home/bin/7linden-at-home) directly and look at its return value.

**Comment by libengine** [comment]
function is still present, but call of it is commented out.
apt-proxy-client depends on 7linden-at-home now.

**Comment by fwolfst** [comment]
oh yes, great.
